/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import BottomViewExt from "./uiExt/BottomViewExt"
import DimageViewExt from "./uiExt/DimageViewExt"
import GameViewExt from "./uiExt/GameViewExt"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=1334;
    static height:number=750;
    static scaleMode:string="fixedheight";
    static screenMode:string="horizontal";
    static alignV:string="middle";
    static alignH:string="center";
    static startScene:any="DimageView.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("uiExt/BottomViewExt.ts",BottomViewExt);
        reg("uiExt/DimageViewExt.ts",DimageViewExt);
        reg("uiExt/GameViewExt.ts",GameViewExt);
    }
}
GameConfig.init();